remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins: [jekyll-include-cache]
minimal_mistakes_skin    : "contrast" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
